version: '3.8'

services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '5000:5000'
    environment:
      - NODE_ENV=development
      - PORT=5000
      - API_PREFIX=/api
      - API_VERSION=v1
      - JWT_SECRET=dev-secret-key
      - CORS_ORIGIN=http://localhost:3000
      - LOG_LEVEL=debug
      - DATABASE_URL=postgresql://user:password@db:5432/node_ts_api?schema=public
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    command: npm run dev
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: node_ts_api
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data_dev:
